const EErrors = {
  DATABASE_ERRROR: 'DATABASE_ERROR',
  INVALID_TYPE_ERROR: 'INVALID_TYPE_ERROR',
  ROUTING_NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404
}

export default EErrors
